language: android
android:
    components:
        - platform-tools
        - tools
        - build-tools-23.0.3
        - android-23

        #- extra
        - extra-android-support
        - extra-android-m2repository
        #- extra-google-m2repository
        #- extra-google-google_play_services

        # Specify at least one system image,
        # if you need to run emulator(s) during your tests
        #- sys-img-armeabi-v7a-android-23
install:
    - true
before_install:
    - chmod +x gradlew